apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: statusboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: seumg9526/statusboard-backend:latest
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mariadb://mariadb:3306/status_board
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: statusboard
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
