apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        {{- if .Values.monitoring.prometheus.enabled }}
        "prometheus.io/scrape": "{{ .Values.monitoring.prometheus.annotations.scrape }}"
        "prometheus.io/path": "{{ .Values.monitoring.prometheus.annotations.path }}"
        "prometheus.io/port": "{{ .Values.monitoring.prometheus.annotations.port }}"
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "statusboard.fullname" . }}-db
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "statusboard.fullname" . }}-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "statusboard.fullname" . }}-db
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.env.backend.SPRING_JPA_HIBERNATE_DDL_AUTO | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.backend.SPRING_PROFILES_ACTIVE | quote }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}

