apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "statusboard.name" . }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "statusboard.name" . }}
        app.kubernetes.io/component: backend
      annotations:
        {{- if .Values.monitoring.prometheus.enabled }}
        "prometheus.io/scrape": "{{ .Values.monitoring.prometheus.annotations.scrape }}"
        "prometheus.io/path": "{{ .Values.monitoring.prometheus.annotations.path }}"
        "prometheus.io/port": "{{ .Values.monitoring.prometheus.annotations.port }}"
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z statusboard-mariadb {{ .Values.service.mariadb.port }}; do
                echo "Waiting for MariaDB..."
                sleep 2
              done
      containers:
        - name: backend
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          env:
            # ⬇️ Secret에서 URL을 가져오는 대신, values.yaml의 값을 직접 사용하도록 수정했습니다.
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.backend.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "statusboard.fullname" . }}-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "statusboard.fullname" . }}-db
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.env.backend.SPRING_JPA_HIBERNATE_DDL_AUTO | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.backend.SPRING_PROFILES_ACTIVE | quote }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
